### ISSUE TITLE
Cloud Search Query API is only available to user accounts with the Cloud Search Platform license.

### ISSUE THREAD

**Issue by mudassirijaz786** [googleworkspace/cloud-search-samples#29]
I have an admin account admin@example.com for google cloud searching, I really don't know why I'm getting an error.

![Screenshot from 2021-08-30 11-56-33](https://user-images.githubusercontent.com/49415042/131298542-e5cc8ea5-0ba8-4b7c-80e8-d57f2023cda8.png)

**Comment by sqrrrl** [comment]
From the error, It looks like you're authorizing as a service account, not as an end user. Service accounts aren't normal members of the domain and don't have licenses.

In the future, please use this issue tracker only for bugs with the samples. For more general how-to questions try StackOverflow, of if you have an enterprise license you can also contact support.
